### PR TITLE
Add buffering for all output to improve performance with many small strings

### PR DESCRIPTION
**Pull request by ribbons**
The project I'm working on at the moment builds a fairly large table a cell at a time, which takes a noticeable amount of time to load in a browser due to the small packets being sent across the network.

I propose to update `WebServer::write(uint8_t)` to write to a buffer instead of sending single characters (or short strings) as small packets.  This PR also removes the other signatures of `write` so that the base ones in the `Print` class (which call `write(uint8_t)`) are used instead and simplifies the `writeP`/`printP` definitions to do this too.

This greatly improves the performance of pages which are built from a large number of small strings or values at the expense of a small additional amount of memory (which defaults to 32k but can be adjusted with the use of a new macro called `WEBDUINO_OUTPUT_BUFFER_SIZE`) and also saves 86 bytes of flash in my particular project into the bargain.

### CODE REVIEW

**Comment by unwiredben** [comment]
Seems like a good patch to me... does this require a certain version of the Arduino library code in order to use the byte write call from the print methods?

**Comment by ribbons** [comment]
Ah, good point - I hadn't thought of that.  Have had a quick check and by the looks of it the `Print::print` methods have called `write(uint8_t)` for each character in strings passed to them since the class was initially added in arduino/Arduino@1a89112e4576a736759b12ba1a76e3140ab47771, so think we should be okay.

**Comment by ribbons** [comment]
@unwiredben Is there anything else that I can clarify or any adjustments that I should make to this PR before it is okay to merge?

**Comment by unwiredben** [comment]
oh, sorry --- just been very busy.  I'll merge today.

**Pull request merged**
