### PR TITLE
Web_AjaxRGB.pde modified to use jQuery Mobile instead of jQuery UI

### PR DESCRIPTION
**Pull request by ronnqvist**
Glad you enjoyed Web_AjaxRGB.pde well enough to pull it into your project. I was going to upgrade it to use jQuery Mobile, but since my jQuery Mobile solution seems to tilt my Arduino a bit more often I decided to make a copy instead. (Read comment in code for more info.) Anyways, here's a demo video of how it looks in action: http://www.youtube.com/watch?v=5te8BNKRcl8

PS. If you have any idea about how to prevent the Arduino from hanging when getting too many ajax requests, I'd be very happy... right now I've tried to solve the problem by making ajax requests time out fast.

### CODE REVIEW

**Comment by sirleech** [comment]
Nice work! Thanks for your work on this and I've added you as a contributor.

**Comment by ronnqvist** [comment]
Thanks! I'll close my own fork then and push to yours in the future. However, I think I won't do anything to this project for a while now... and when I do there are a couple of problems that I'm facing.

One is that this flood of ajax requests isn't really well handled by the Arduino just a few of them get through and the Arduino easily hangs. (I'm quite noob on the Arduino-coding side, so I don't really know how to make it handle them better... so I just tried making the javascript more graceful.)

Another issue is that it's not really ideal to always link to CDN:s for JS/CSS code, it means that the app can't work without an internet connection to the lan and more importantly it's hard to have a lot of custom code. Solutions to provide code from a microSD card would be crucial... I'm sure that can be done with Webduino but the project TinyWebServer centers around this functionality. However I decided to start off with Webduino since the Web_AjaxBuzzer.pde example code was pretty close to what I needed, and Webduino also seems to have more history and a more vibrant community (TinyWebServer seems to pretty much be a one-guy project).

PS. Don't know if this is the right place for a lengthy discussion about this... but at least it all relates to the file I committed. :)

**Comment by ronnqvist** [comment]
Couldn't help myself, researched and experimented a bit and the only good palette-solution for smartphones that I could find was this combination: https://github.com/ronnqvist/farbtastic/blob/master/demo/2-jqmobile/demo1.html

Next step, when it happends is to try implementing that panel to control RGB leds. Then however, I will need to be able to store JS and probably other files too on the Arduino (microSD card). So resolving that issue would be the first small step before that. But now I'll set the project aside for a while, l8r! :)

**Comment by SeanBannister** [comment]
I noticed someone talking about SD card support on the old Google Project page http://code.google.com/p/webduino/issues/detail?id=10 this is something I'm also interested in and currently trying out TinyWebServer.

**Pull request merged**
