### PR TITLE
Add Following Supports in the library

### PR DESCRIPTION
**Pull request by farooqsheikhpk**
1. 415 Unsupported Media Type
2. 400 Bad Request
3. Read Full POST Body (useful to read JSON Body) - bool readPOSTbody(char *body, int bodyLen)

### CODE REVIEW

**Comment by unwiredben** [comment]
It's impossible to evaluate your pull request -- it looks like you reformatted the whole file (or at least changed the line endings), and GitHub isn't handling that well.

**Comment by farooqsheikhpk** [comment]
Hi,
OK. I will resubmit to fix this white spaces issue.

## 

Best Regards
Farooq Sheikh
Banckle Platform Team Lead
http://banckle.com/
Your Customer Services 2.0

**Comment by farooqsheikhpk** [comment]
@unwiredben 
Please check now. 
I have fixed the white space issue. 
https://github.com/farooqsheikhpk/Webduino/commit/171ea4c96395419e27e4a6869c57ceebb5928a3e

**Comment by q2dg** [comment]
What's going on with this?

**Comment by unwiredben** [comment]
The pull request needs to be resubmitted with the fixed commit -- this is still the version with the line-ending problems.

**Pull request closed without merging**
